// <auto-generated />
using System;
using AiesecBiH.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AiesecBiH.Migrations
{
    [DbContext(typeof(AiesecContext))]
    [Migration("20210925194558_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AiesecBiH.Database.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FunctionalFieldId")
                        .HasColumnType("int");

                    b.Property<int?>("LocalCommitteeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeUid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalFieldId");

                    b.HasIndex("LocalCommitteeId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedDate = new DateTime(2020, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 11, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            Name = "YSF 2020",
                            TimeUid = 5L
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedDate = new DateTime(2020, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            Name = "LCM",
                            TimeUid = 3L
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedDate = new DateTime(2021, 8, 13, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 10, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            Name = "Lorem",
                            TimeUid = 2L
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedDate = new DateTime(2021, 10, 14, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 10, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            Name = "Event 2",
                            TimeUid = 5L
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedDate = new DateTime(2021, 11, 14, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 3,
                            LocalCommitteeId = 2,
                            Name = "Event 3",
                            TimeUid = 2L
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedDate = new DateTime(2021, 5, 13, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            Name = "Natco",
                            TimeUid = 5L
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedDate = new DateTime(2021, 2, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 3,
                            LocalCommitteeId = 3,
                            Name = "BSA",
                            TimeUid = 10L
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedDate = new DateTime(2020, 12, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 3,
                            LocalCommitteeId = 4,
                            Name = "Event",
                            TimeUid = 7L
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 15, 21, 45, 57, 100, DateTimeKind.Local).AddTicks(7365),
                            DateTime = new DateTime(2021, 9, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            Name = "YSF event",
                            TimeUid = 5L
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedDate = new DateTime(2020, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 7, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            Name = "LCM",
                            TimeUid = 4L
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.EventAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("EventAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(3734),
                            EventId = 1,
                            MemberId = 2
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6290),
                            EventId = 1,
                            MemberId = 3
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6413),
                            EventId = 1,
                            MemberId = 4
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6426),
                            EventId = 1,
                            MemberId = 5
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6433),
                            EventId = 2,
                            MemberId = 2
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6440),
                            EventId = 2,
                            MemberId = 3
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6448),
                            EventId = 2,
                            MemberId = 4
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6456),
                            EventId = 3,
                            MemberId = 5
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6464),
                            EventId = 3,
                            MemberId = 4
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6471),
                            EventId = 4,
                            MemberId = 4
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6478),
                            EventId = 4,
                            MemberId = 3
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6485),
                            EventId = 4,
                            MemberId = 2
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6492),
                            EventId = 4,
                            MemberId = 5
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6499),
                            EventId = 5,
                            MemberId = 10
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6505),
                            EventId = 6,
                            MemberId = 11
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6512),
                            EventId = 6,
                            MemberId = 12
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6519),
                            EventId = 7,
                            MemberId = 10
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Attended = false,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 102, DateTimeKind.Local).AddTicks(6526),
                            EventId = 7,
                            MemberId = 11
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("AiesecBiH.Database.FunctionalField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FunctionalFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "P",
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 70, DateTimeKind.Local).AddTicks(7462),
                            Description = "Functional field for members that lead the organization and local committees.",
                            Name = "Presidency"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "MKT",
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 70, DateTimeKind.Local).AddTicks(9768),
                            Description = "Functional field that engages the target audience, build strong relationships to create value.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "IGV",
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 70, DateTimeKind.Local).AddTicks(9836),
                            Description = "iGV is the department that handles all that is related starting from attracting Exchange Participants (EPs) for our local projects.",
                            Name = "Incomming Global Volounteere"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "OGV",
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 70, DateTimeKind.Local).AddTicks(9852),
                            Description = "Outgoing Global Volunteer team is responsible for creating local strategies on converting opens to applicants.",
                            Name = "Outgoing Global Volounteere"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "PD",
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 70, DateTimeKind.Local).AddTicks(9866),
                            Description = "Partnership Development is the department responsible for raising and maintaining the contact with our partners with activities ranging from cold calls.",
                            Name = "Partnership Development"
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.LocalCommittee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstablishmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalCommittees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2723),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2116),
                            Name = "  "
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2823),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2807),
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2836),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2832),
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2849),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(2845),
                            Name = "Zenica"
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FunctionalFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalCommitteeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.HasIndex("FunctionalFieldId");

                    b.HasIndex("LocalCommitteeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 83, DateTimeKind.Local).AddTicks(757),
                            EmailAddress = "aiesec@tej.com",
                            FirstName = "Admin",
                            FunctionalFieldId = 1,
                            Gender = "M",
                            LastName = "Admin",
                            LocalCommitteeId = 1,
                            PasswordHash = "gtPBPEc8hXVnK7mJUSDTZrw4pPb+xIZrgl2uEylHr5+4nVQlqitUANuJo2eGIIGK6GsP76lww6oSL2hcD+gZLA==",
                            PasswordSalt = "7HBe2/jcghPvbgCwi8GZkQ==",
                            PhoneNumber = "03355123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "Dobrinjska 12",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(5543),
                            EmailAddress = "amel@gmail.com",
                            FirstName = "Amel",
                            FunctionalFieldId = 1,
                            Gender = "M",
                            LastName = "Music",
                            LocalCommitteeId = 2,
                            PasswordHash = "m2bDtswYeVkbwUM1UNji3DHqvmIUVEeLD3+XvgZuj5hBS95/fnuJAq1mi7qQJr5LUb8qh9KFXnqdfv/M3ZvHLg==",
                            PasswordSalt = "XM7AIBCgnne+uODKXQt73g==",
                            PhoneNumber = "062123344",
                            RoleId = 2,
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "Safeta Zajke 298",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(7884),
                            EmailAddress = "sulejman.tutnjevic98@gmail.com",
                            FirstName = "Sulejman",
                            FunctionalFieldId = 2,
                            Gender = "M",
                            LastName = "Tutnjevic",
                            LocalCommitteeId = 2,
                            PasswordHash = "bd9/zzaC/T0B0V3JWKkVasacRt+hhUg8npcHhbchT+vATtZqPbtwVPRO95omKgYT/GehkehrMOPS4yYuj8hQPQ==",
                            PasswordSalt = "NsKRPUtzH0q9vE/YJYv2ig==",
                            PhoneNumber = "062123344",
                            RoleId = 3,
                            Username = "sulejmantutnjevic"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Address = "Zahira Panjete 298",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8149),
                            EmailAddress = "tarik.bucan98@gmail.com",
                            FirstName = "Tarik",
                            FunctionalFieldId = 2,
                            Gender = "M",
                            LastName = "Bucan",
                            LocalCommitteeId = 2,
                            PasswordHash = "5zxPdrpi1qNh6KAwQuEWQPZGuRpzo6exlLbYXvXuo9wK6O6yP5f4UHgVqQnrS7xbCqtXtGH3aqtJriwVVo3tkQ==",
                            PasswordSalt = "+zZMSNBXTltZPtu2yhfO0w==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "user1"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Address = "Grbavica 12",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8263),
                            EmailAddress = "selma.idic@aiesec.com",
                            FirstName = "Selma",
                            FunctionalFieldId = 2,
                            Gender = "M",
                            LastName = "Idic",
                            LocalCommitteeId = 2,
                            PasswordHash = "4o+vacvmO416UPGh4LSTz07Vn8ux45o23s5efryxG4K/uExSbEzyo5RML6WSBNRojk7/7fSnft9ELEN0Q7feZg==",
                            PasswordSalt = "vxKy7hp+DPkWezbWMPKXcA==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "selmaidic"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Address = "Doglodi 12",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8350),
                            EmailAddress = "emir.zukic@gmail.com",
                            FirstName = "Emir",
                            FunctionalFieldId = 2,
                            Gender = "M",
                            LastName = "Zukic",
                            LocalCommitteeId = 2,
                            PasswordHash = "iUaE/HEBoBmvcSB4smPXAs2ZDrxMKOKGi6vbW4klAslZrvzlx66xRX9CRMNd2Tnl9aV6qhscgs351AVdaTrnSw==",
                            PasswordSalt = "fikBh+/ZKF208t88/AheZg==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "emirzukic"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Address = "Grbavica 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8437),
                            EmailAddress = "doraglinac@gmail.com",
                            FirstName = "Dora",
                            FunctionalFieldId = 3,
                            Gender = "F",
                            LastName = "Glinac",
                            LocalCommitteeId = 2,
                            PasswordHash = "YA6U7lv9bWpmmmA6CPIDidRwtnSfi3HfLYx9moIExJ9c84jQvf6zJBBcEKGRngNrYgSw68tXSp8Mxn/JY9uMig==",
                            PasswordSalt = "J2wb3Rdy4EkeAL9zEpdA7Q==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "doraglinac"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Address = "Borik 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8535),
                            EmailAddress = "nikola.bujak@gmail.com",
                            FirstName = "Nikola",
                            FunctionalFieldId = 3,
                            Gender = "M",
                            LastName = "Bujak",
                            LocalCommitteeId = 2,
                            PasswordHash = "ifcnGmOEunAF8MtJ/jgfRKpIedJ0U5r+EbzqtmGr4xSJk8D9C8/605YwYiwNXE3koQ/LRc/qjPkvTX1gaZPOhw==",
                            PasswordSalt = "YsjfE5EAOITTM+t1fF3oVQ==",
                            PhoneNumber = "062123344",
                            RoleId = 3,
                            Username = "nikolabujak"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Address = "Gospodska 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8617),
                            EmailAddress = "nevzudindosic@gmail.com",
                            FirstName = "Nevzudin",
                            FunctionalFieldId = 3,
                            Gender = "M",
                            LastName = "Dosic",
                            LocalCommitteeId = 2,
                            PasswordHash = "/i3mz/5voA7E4Y6H5iKAjANJLKNwP8dAPVrwlSsml1whVG1rOkQCEDL6Yy0Ev+IN/fPffMwifwbkSDAMbEC4kA==",
                            PasswordSalt = "8ckzC0KTETAtbJTAEsJ/vA==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "nevzudindosic"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Address = "Mostar 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8691),
                            EmailAddress = "klarazovko@gmail.com",
                            FirstName = "Klara",
                            FunctionalFieldId = 4,
                            Gender = "F",
                            LastName = "Zovko",
                            LocalCommitteeId = 2,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "5AeikAcWnULuu2eazHq0mA==",
                            PhoneNumber = "062123344",
                            RoleId = 3,
                            Username = "klarazovko"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Address = "Centar 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8817),
                            EmailAddress = "hanakulenovic@gmail.com",
                            FirstName = "Hana",
                            FunctionalFieldId = 5,
                            Gender = "F",
                            LastName = "Kulenovic",
                            LocalCommitteeId = 2,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "5AeikAcWnULuu2eazHq0mA==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "hanakulenovic"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8899),
                            EmailAddress = "test3@gmail.com",
                            FirstName = "Haris",
                            FunctionalFieldId = 3,
                            Gender = "M",
                            LastName = "Brulic",
                            LocalCommitteeId = 3,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "dx1TH+nwWs1hBVoYg/tjrw==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "harisbrulic"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(8972),
                            EmailAddress = "ajdink@gmail.com",
                            FirstName = "Ajdin",
                            FunctionalFieldId = 4,
                            Gender = "M",
                            LastName = "Kahrimanovic",
                            LocalCommitteeId = 3,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "ugnW2rXmmz5h8J2RgD7etA==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "ajdink"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9040),
                            EmailAddress = "denis@gmail.com",
                            FirstName = "Denis",
                            FunctionalFieldId = 5,
                            Gender = "M",
                            LastName = "Music",
                            LocalCommitteeId = 3,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "v458vszHzSpoTEJJmHwrJQ==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "denismusic"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9110),
                            EmailAddress = "elmirbabovic@gmail.com",
                            FirstName = "Elmir",
                            FunctionalFieldId = 4,
                            Gender = "M",
                            LastName = "Babovic",
                            LocalCommitteeId = 3,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "D6o7rv+/6IsvmvBz5qlrgA==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "elmirbabovic"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Address = "Test 6",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9198),
                            EmailAddress = "irmasaric@gmail.com",
                            FirstName = "Irma",
                            FunctionalFieldId = 2,
                            Gender = "M",
                            LastName = "Saric",
                            LocalCommitteeId = 4,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "OhY/1Yt6VeargM0750rDPw==",
                            PhoneNumber = "0621112222",
                            RoleId = 4,
                            Username = "irmasaric"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Address = "Dobrinja 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9266),
                            EmailAddress = "test2@gmail.com",
                            FirstName = "Ajla",
                            FunctionalFieldId = 3,
                            Gender = "M",
                            LastName = "Brulic",
                            LocalCommitteeId = 4,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "OhY/1Yt6VeargM0750rDPw==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "ajlabrulic"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9332),
                            EmailAddress = "test1@gmail.com",
                            FirstName = "Haris",
                            FunctionalFieldId = 4,
                            Gender = "M",
                            LastName = "Brulic",
                            LocalCommitteeId = 4,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "OhY/1Yt6VeargM0750rDPw==",
                            PhoneNumber = "062123344",
                            RoleId = 4,
                            Username = "harisbrulic"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Address = "Test 4",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 91, DateTimeKind.Local).AddTicks(9399),
                            EmailAddress = "nejiravrana@gmail.com",
                            FirstName = "Nejira",
                            FunctionalFieldId = 3,
                            Gender = "Z",
                            LastName = "Vrana",
                            LocalCommitteeId = 4,
                            PasswordHash = "ePVpx3fKSyKCVSzlTH2tXUs9CzOWSY2LpNzplugzYWDCZzoQeIjpfzJaVwcObCkyJ+SwbmOuHA8gDAs1Xeuf6g==",
                            PasswordSalt = "OhY/1Yt6VeargM0750rDPw==",
                            PhoneNumber = "062567948",
                            RoleId = 4,
                            Username = "nejiravrana"
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Notice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Notices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Otvaraju se prijave za poziciju MCP iduceg mandata.",
                            CreatedDate = new DateTime(2019, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            Title = "Prijava za poziciju"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Suspendisse convallis non orci sed viverra. Sed ac sapien vitae sapien cursus tincidunt quis id nibh. Quisque dictum et dolor in lobortis. Nulla turpis ligula, vehicula vel elit commodo, euismod fermentum lacus. Donec ligula turpis, maximus at velit a, fringilla lobortis ligula.",
                            CreatedDate = new DateTime(2019, 11, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            Title = "Fusce aliquam mi vehicula"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Nunc in egestas dui. Fusce efficitur enim nunc, sit amet mattis dolor efficitur ac. Proin pulvinar urna non elit vestibulum,",
                            CreatedDate = new DateTime(2020, 8, 8, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            Title = "Nunc imperdiet urna ac orci"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            CreatedDate = new DateTime(2020, 10, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            Title = "Fusce erat est fermentum"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Maecenas in tellus metus. Integer commodo turpis a massa tincidunt vulputate. Integer lacus ligula, tristique nec mi a, ultrices egestas lectus. Etiam rutrum et turpis nec auctor.",
                            CreatedDate = new DateTime(2021, 4, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            Title = "Nunc quis quam pulvinar"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Nam augue augue, luctus vitae nisl at, finibus dictum orci. Nunc in egestas dui. Fusce efficitur enim nunc, sit amet mattis dolor efficitur ac. Proin pulvinar urna non elit vestibulum.",
                            CreatedDate = new DateTime(2021, 5, 22, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            Title = "Aliquam vehicula enim"
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstablishmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocalCommitteeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalCommitteeId");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "Trg Alije Izetbegovica 2",
                            Capacity = 20,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 74, DateTimeKind.Local).AddTicks(8787),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(433),
                            LocalCommitteeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "Ulica 3",
                            Capacity = 10,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(904),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(964),
                            LocalCommitteeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "Ulica 4",
                            Capacity = 20,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(989),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(994),
                            LocalCommitteeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Address = "Ulica 22",
                            Capacity = 20,
                            CreatedDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(1007),
                            EstablishmentDate = new DateTime(2021, 9, 25, 21, 45, 57, 75, DateTimeKind.Local).AddTicks(1011),
                            LocalCommitteeId = 4
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Mandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AiesecBiH.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Admin",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "P",
                            Name = "President"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "TL",
                            Name = "TeamLeader"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "TM",
                            Name = "TeamMember"
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfExecution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Executed")
                        .HasColumnType("bit");

                    b.Property<int>("FunctionalFieldId")
                        .HasColumnType("int");

                    b.Property<int>("LocalCommitteeId")
                        .HasColumnType("int");

                    b.Property<int>("MemberCreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberExecutorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalFieldId");

                    b.HasIndex("LocalCommitteeId");

                    b.HasIndex("MemberCreatorId");

                    b.HasIndex("MemberExecutorId");

                    b.HasIndex("RoleId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedDate = new DateTime(2019, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 11, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 2,
                            MemberExecutorId = 2,
                            Name = "Sastanak sa partnerima",
                            Priority = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedDate = new DateTime(2020, 9, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 11, 11, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 2,
                            MemberExecutorId = 2,
                            Name = "Kontaktirati Dom armije",
                            Priority = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedDate = new DateTime(2020, 10, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 2,
                            MemberExecutorId = 3,
                            Name = "Odrzati intervju sa novim clanovima",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedDate = new DateTime(2020, 10, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 11, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 3,
                            MemberExecutorId = 3,
                            Name = "Edukacija novih clanova",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 1, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 1, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 3,
                            MemberExecutorId = 1,
                            Name = "Priprema za YSF",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedDate = new DateTime(2021, 5, 13, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 7, 11, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 3,
                            Name = "SWAT analiza za ITA",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedDate = new DateTime(2021, 12, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 6, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 5,
                            Name = "Kontaktirati govornike za YSF",
                            Priority = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedDate = new DateTime(2020, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 5,
                            MemberExecutorId = 7,
                            Name = "Odlazak na aerodrom",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 5,
                            MemberExecutorId = 6,
                            Name = "Sastanak sa Coca-Colom",
                            Priority = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 3,
                            MemberCreatorId = 5,
                            MemberExecutorId = 7,
                            Name = "Kontaktirati sponzore za BSA",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 4,
                            LocalCommitteeId = 4,
                            MemberCreatorId = 5,
                            MemberExecutorId = 6,
                            Name = "Kupiti panel za BSA",
                            Priority = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 4,
                            MemberCreatorId = 5,
                            MemberExecutorId = 7,
                            Name = "Kontaktirati sponzore za hranu, BSA",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreatedDate = new DateTime(2021, 1, 10, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2021, 2, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 3,
                            LocalCommitteeId = 3,
                            MemberCreatorId = 5,
                            MemberExecutorId = 6,
                            Name = "Kontaktirati Dom Armije za YSF",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreatedDate = new DateTime(2020, 9, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2020, 11, 11, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 2,
                            MemberExecutorId = 2,
                            Name = "Novi task",
                            Priority = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 21, 21, 45, 57, 98, DateTimeKind.Local).AddTicks(3094),
                            Deadline = new DateTime(2020, 10, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 4,
                            MemberExecutorId = 3,
                            Name = "Uplatiti na racun",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 22, 21, 45, 57, 98, DateTimeKind.Local).AddTicks(3184),
                            Deadline = new DateTime(2020, 11, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = true,
                            FunctionalFieldId = 1,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 4,
                            MemberExecutorId = 3,
                            Name = "Kontaktirati stare clanove",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 23, 21, 45, 57, 98, DateTimeKind.Local).AddTicks(3203),
                            Deadline = new DateTime(2021, 1, 9, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 3,
                            Name = "Priprema banera",
                            Priority = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreatedDate = new DateTime(2021, 9, 23, 21, 45, 57, 98, DateTimeKind.Local).AddTicks(3221),
                            Deadline = new DateTime(2021, 7, 11, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vestibulum semper lacus vel dolor consectetur, eu consequat lorem hendrerit.",
                            Executed = false,
                            FunctionalFieldId = 2,
                            LocalCommitteeId = 2,
                            MemberCreatorId = 3,
                            Name = "Provjeriti cijene majica",
                            Priority = 2,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("AiesecBiH.Database.Event", b =>
                {
                    b.HasOne("AiesecBiH.Database.FunctionalField", "FunctionalField")
                        .WithMany("Events")
                        .HasForeignKey("FunctionalFieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.LocalCommittee", "LocalCommittee")
                        .WithMany("Events")
                        .HasForeignKey("LocalCommitteeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FunctionalField");

                    b.Navigation("LocalCommittee");
                });

            modelBuilder.Entity("AiesecBiH.Database.EventAttendance", b =>
                {
                    b.HasOne("AiesecBiH.Database.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AiesecBiH.Database.FileModel", b =>
                {
                    b.HasOne("AiesecBiH.Database.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AiesecBiH.Database.Member", b =>
                {
                    b.HasOne("AiesecBiH.Database.FunctionalField", "FunctionalField")
                        .WithMany("Members")
                        .HasForeignKey("FunctionalFieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AiesecBiH.Database.LocalCommittee", "LocalCommittee")
                        .WithMany("Members")
                        .HasForeignKey("LocalCommitteeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalField");

                    b.Navigation("LocalCommittee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AiesecBiH.Database.Notice", b =>
                {
                    b.HasOne("AiesecBiH.Database.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AiesecBiH.Database.Office", b =>
                {
                    b.HasOne("AiesecBiH.Database.LocalCommittee", "LocalCommittee")
                        .WithMany("Offices")
                        .HasForeignKey("LocalCommitteeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LocalCommittee");
                });

            modelBuilder.Entity("AiesecBiH.Database.Task", b =>
                {
                    b.HasOne("AiesecBiH.Database.FunctionalField", "FunctionalField")
                        .WithMany()
                        .HasForeignKey("FunctionalFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.LocalCommittee", "LocalCommittee")
                        .WithMany()
                        .HasForeignKey("LocalCommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.Member", "MemberCreator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("MemberCreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AiesecBiH.Database.Member", "MemberExecutor")
                        .WithMany("ExecutedTasks")
                        .HasForeignKey("MemberExecutorId");

                    b.HasOne("AiesecBiH.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalField");

                    b.Navigation("LocalCommittee");

                    b.Navigation("MemberCreator");

                    b.Navigation("MemberExecutor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AiesecBiH.Database.FunctionalField", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("AiesecBiH.Database.LocalCommittee", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Members");

                    b.Navigation("Offices");
                });

            modelBuilder.Entity("AiesecBiH.Database.Member", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("ExecutedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
